### ISSUE TITLE
Change naming "agg" to "stat"?

### ISSUE THREAD

**Issue by Datseris** [JuliaClimate/ClimateBase.jl#20]
So far I have created convenience functions like `timemean`, but tried to always have a general version called e.g. `timeagg` where the function that "summarizes" the data can be any arbitrary function like `sum, mean, std`.

But I am not a native English speaker. So far, I thought "aggregation" was this process of taking a bunch of numbers and describing them with a single number, e.g. the sum or the mean. But I've just found that aggregation means "grouping".

Should we change the naming aggregation I've used and the shorthand `agg`, to something else? And what is that something else? I thought of `stat`, but I am still not sure...

**Comment by Datseris** [comment]
@Balinus can you please chime in here?

**Comment by Balinus** [comment]
Sorry, just saw the issue actually, thanks for the ping. Generally speaking, aggregation can be used if the grouped data aggregated into a single statistical value. So, I don't mind it!

**Comment by Balinus** [comment]
But, looking at it, I'd much prefer `stat` than `agg`.

**Comment by Datseris** [comment]
Okay that is good for me as well, and then I'll do it in 0.8!

**Comment by Datseris** [comment]
I did this change internally but it doesn't look that good. `timestat` and `spacestat` feel more like names that would provide inforemation about the time dimension or space dimension instead of do some kind of statistical operation on it. I'll leave the `agg` versions in for now later down the road we see how they look.
