### ISSUE TITLE
Create en ensemble type

### ISSUE THREAD

**Issue by Balinus** [JuliaClimate/ClimateBase.jl#3]
Formalizing an `ensemble` type will be useful to standardize the methods based on ensemble: ensemble mean, variance, plots, regridding on a common grid.

```julia
struct ensemble
   Ensemble::Array{ClimGrid}
   Name::String
   Map # map definition (regridding might be part of the constructor? which means that the mapping definition would be contained into each ClimGrid and will be similar)
end
```

Thoughts?

**Comment by Datseris** [comment]
No reason to exist, it can be represented as a `Vector{ClimArray}`. Standard Julia syntax can be used for "ensemble mean/variance". E.g. ensemble global mean would be
```julia
E = [ClimArray("ensemble_$i.nc") for i in 1:10]
global_mean = mean(spacemean(X) for X in E)
```

The more standard Julia syntax can be used, the less developer work we have to do, and the less a user has to learn, making everything more extendable, better tested, and simpler to learn.

**Comment by Balinus** [comment]
I'd suggest adding the code snippets into the documentation under a "Ensemble statistics". What do you think?

**Comment by Datseris** [comment]
Sure, I'm reopening as documentation issue
