### ISSUE TITLE
Rename the function that loads input data

### ISSUE THREAD

**Issue by Datseris** [JuliaClimate/ClimateBase.jl#52]
At the moment input data are loaded with a function called `ClimArray`. This is not a good design idea. `ClimArray` should be reserved exclusively for the constructor.

What is a better name for a function that directly loads `.nc` data and outputs them as a `ClimArray`?

**Comment by Balinus** [comment]
Perhaps something that follows FileIO.jl?
https://github.com/JuliaIO/FileIO.jl

**Comment by Datseris** [comment]
Good idea, however I think that `FileIO` is really for disk-to-memory direct things, so NCDatasets.jl should be using that interface. We could use `ncread` and `ncwrite` though as the names here!
