### ISSUE TITLE
version conflicts with julia 1.4.1

### ISSUE THREAD

**Issue by Eisbrenner** [JuliaClimate/ClimateBase.jl#55]
Hi, just found this project and I am looking forward to use it in the future. Today I just wanted to have a quick sneak peek but couldn't because it seems like the default registry only supplies version 0.6.0 when using julia 1.4.1.

So I see that version 1.5 is specified in the `Project.toml` but the tests seemingly run on Julia 1.x too? Further, the error message down below seems to suggest that only version `< 0.6` is allowed.

I'll see to install julia 1.5 another day, but thought this might be of interest for you?

```julia
julia> VERSION
v"1.4.1"
```
```julia
 pkg> status
Status `/.../Project.toml`
  [35604d93] ClimateBase v0.6.0
  [85f8d34a] NCDatasets v0.11.3
```

```julia
pkg> add ClimateBase@0.11.3
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ClimateBase [35604d93]:
 ClimateBase [35604d93] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0-0.9.2, 0.10.0-0.10.5, 0.11.0-0.11.3] or uninstalled
 ├─restricted to versions 0.11.3 by an explicit requirement, leaving only versions 0.11.3
 └─restricted by julia compatibility requirements to versions: [0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0] or uninstalled — no versions left
```

**Comment by Balinus** [comment]
@Datseris will be able to confirm, but as far as I can remember, I think that some features were not properly functioning with Julia < 1.5.

**Comment by Datseris** [comment]
https://github.com/JuliaClimate/ClimateBase.jl/blob/master/.github/workflows/ci.yml#L18

actually tests run on Julia 1.5, and now on julia 1.6 which is latest stable. 1.6 is the new LTS version of Julia, I personally do not see a reason to support previous versions.
